# Generated by Django 4.2 on 2026-07-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity_g',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=0, help_text='Cantidad en gramos (ingredientes por peso) o en unidades (ingredientes por unidad)'),
            preserve_default=False,
        ),
    ]
