# Generated by Django 4.2 on 2026-07-14 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0002_ingredient_calories_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_remove_recipeingredient_quantity_g_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_builtin', models.BooleanField(default=False, help_text='Identifica la lista Default global (única)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipes', models.ManyToManyField(blank=True, related_name='lists', to='recipes.recipe')),
                ('user', models.ForeignKey(blank=True, help_text='Nulo para la lista Default global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_builtin', models.BooleanField(default=False, help_text='Identifica la lista Default global (única)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='lists', to='ingredients.ingredient')),
                ('user', models.ForeignKey(blank=True, help_text='Nulo para la lista Default global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipelist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_builtin', True)), fields=('is_builtin',), name='unique_builtin_recipe_list'),
        ),
        migrations.AlterUniqueTogether(
            name='recipelist',
            unique_together={('user', 'name')},
        ),
        migrations.AddConstraint(
            model_name='ingredientlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_builtin', True)), fields=('is_builtin',), name='unique_builtin_ingredient_list'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientlist',
            unique_together={('user', 'name')},
        ),
    ]
