# Generated by Django 4.2 on 2026-07-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_type',
            field=models.CharField(choices=[('weight', 'Por 100 g'), ('unit', 'Por unidad')], default='weight', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_label',
            field=models.CharField(blank=True, help_text="Nombre de la unidad (ej. 'huevo', 'rebanada')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(blank=True, help_text='Calorías por cada 100 g', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_g',
            field=models.FloatField(blank=True, help_text='Carbohidratos en gramos (g) por 100 g', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_g',
            field=models.FloatField(blank=True, help_text='Grasas en gramos (g) por cada 100 g', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_g',
            field=models.FloatField(blank=True, help_text='Proteína en gramos (g) por cada 100 g', null=True),
        ),
    ]
