# Generated by Django 4.2 on 2026-06-13 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('supplement', 'Supplement')], max_length=20)),
                ('name', models.CharField(blank=True, help_text='Requerido para snack y supplement', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_meals', to='plans.dailyplan')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='planmeal',
            constraint=models.UniqueConstraint(condition=models.Q(('meal_type__in', ['breakfast', 'lunch', 'dinner'])), fields=('daily_plan', 'meal_type'), name='unique_main_meal_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planmeal',
            constraint=models.UniqueConstraint(condition=models.Q(('meal_type__in', ['snack', 'supplement'])), fields=('daily_plan', 'meal_type', 'name'), name='unique_snack_supplement_name_per_plan'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('user', 'date', 'name')},
        ),
    ]
