# Generated by Django 4.2 on 2026-06-13 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Masculino"), ("female", "Femenino")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True, help_text="Altura en centímetros", null=True
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentario (poco o nada de ejercicio)"),
                            ("light", "Ligero (ejercicio 1-3 días/semana)"),
                            ("moderate", "Moderado (ejercicio 3-5 días/semana)"),
                            ("active", "Activo (ejercicio 6-7 días/semana)"),
                            ("very_active", "Muy activo (ejercicio intenso diario)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose_weight", "Bajar de peso"),
                            ("maintain", "Mantener peso"),
                            ("gain_weight", "Subir de peso"),
                            ("build_muscle", "Construir músculo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dietary_restrictions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.FloatField()),
                ("date", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_history",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("profile", "date")},
            },
        ),
    ]
