# Generated by Django 4.2 on 2026-06-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dietary_restrictions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
